---

# node(s) specifications
node1_ip: x.x.x.x
node1_type: server
node2_ip: x.x.x.x
node2_type: agent

# SSH user
ssh_user: ubuntu

# SSH Key
ssh_key_path: /tmp/id_rsa

# AWS integration (when using ha and elb)
aws_enabled: false

# RKE2 installation method (for cross installarion only supoport tar)
rke2_method: tar

# RKE2 version 
rke2_version: v1.21.5+rke2r2

# RKE2 channel
rke2_channel: stable

# RKE2 repository URL
rke2_channel_url: https://update.rke2.io/v1-release/channels

# HA mode - disabled, keepalived, elb (aws only)
rke2_ha_mode: disabled

# API Server port
rke2_apiserver_port: 6443

# Master node(s) taint
# rke2_node_taint: true

# Pre-shared secret token for node registration
rke2_token: defaultSecret12345

# Do not deploy components or delete any components - rke2-canal, rke2-coredns, rke2-ingress-nginx, rke2-kube-proxy, rke2-metrics-server
rke2_disabled:

# Custom manifests path for RKE2 installation
rke2_custom_manifests_path:

# Custom containerd image registry
rke2_containerd_registry: false

# Kubernetes API server flags - https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver
rke2_apiserver_args: []

# Override default containerd snapshotter
rke2_containerd_snapshooter: overlayfs
