---

# node(s) specifications can be defined in inventory file

# SSH user
ssh_user: ubuntu

# SSH Key
ssh_key_path: /app/id_rsa

# RKE2 installation method (for cross installation, only supports tar)
rke2_method: tar

# RKE2 version 
rke2_version: v1.21.5+rke2r2

# RKE2 channel
rke2_channel: stable

# RKE2 repository URL
rke2_channel_url: https://update.rke2.io/v1-release/channels

# HA mode - disabled, keepalived, external (aws, gcp, azure or different LB's)
rke2_lb_mode: disabled

# External LB DNS/IP address - If you select HA mode external than you must set rke2_lb_addr
# rke2_lb_addr: external-lb-address

# Use cilium CNI. If this variable not set, default cni will be used.
rke2_cni: cilium

# API Server port
rke2_apiserver_port: 6443

# Master node(s) taint
# rke2_node_taint: true

# Pre-shared secret token for node registration
rke2_token: defaultSecret12345

# Do not deploy components or delete any components - rke2-canal, rke2-coredns, rke2-ingress-nginx, rke2-metrics-server
rke2_disabled_components:

# Custom manifests path for RKE2 installation
rke2_custom_manifests_path:

# Custom containerd image registry
rke2_containerd_registry: false

# Kubernetes API server flags - https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver
rke2_apiserver_args: []

# Override default containerd snapshotter
rke2_containerd_snapshooter: overlayfs

# Override default cluster cidr range
rke2_cluster_cidr: 10.42.0.0/16

# Override default service cidr range
rke2_service_cidr: 10.43.0.0/16

# Override default rke2 cloud controller
rke2_disable_cloud_controller: false
