- name: Create a symbolic link for kubectl as k
  file:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/bin/k
    state: link

- name: Create a symbolic link for kubectl as kubectl
  file:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/bin/kubectl
    state: link

- name: Create a .kube directory if does not exists
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0700'

- name: Create a symbolic link for kubeconfig
  file:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ~/.kube/config
    state: link

- name: Install helm 
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Clone kubectl
  git:
    repo: https://github.com/ahmetb/kubectx
    dest: /opt/kubectx

- name: Create a symbolic link for kubectx as kubectx
  file:
    src: /opt/kubectx/kubectx
    dest: /usr/local/bin/kubectx
    state: link

- name: Create a symbolic link for kubectx as kx
  file:
    src: /opt/kubectx/kubectx
    dest: /usr/local/bin/kx
    state: link

- name: Create a symbolic link for kubens as kubens
  file:
    src: /opt/kubectx/kubens
    dest: /usr/local/bin/kubens
    state: link

- name: Create a symbolic link for kubectx as kn
  file:
    src: /opt/kubectx/kubens
    dest: /usr/local/bin/kn
    state: link

