---

- name: Install Keepalived when HA mode is enabled
  include_tasks: keepalived.yml
  when:
    - rke2_api_ip is defined
    - inventory_hostname is in groups.servers
    - rke2_lb_mode

- name: public fact
  set_fact:
    rke2_api_ip: "{{ groups.servers.0 }}"

- name: Populate services facts
  ansible.builtin.service_facts:
  when:
    - rke2_lb_mode

- name: Check RKE2 version
  ansible.builtin.shell: |
    set -o pipefail
    rke2 --version | grep -E "rke2 version" | awk '{print $3}'
  args:
    executable: /bin/bash
  changed_when: false
  register: installed_rke2_version
  when: '"rke2-server.service" in ansible_facts.services'

- name: Download RKE2 script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2.sh
  when: (rke2_version != ( installed_rke2_version.stdout | default({})))
        or installed_rke2_version is not defined

- name: Set the permissions 
  file:
    dest: /tmp/rke2.sh
    mode: 0700
  when: (rke2_version != ( installed_rke2_version.stdout | default({})))
        or installed_rke2_version is not defined

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory
    owner: root
    group: root
    mode: '0744'
  when: rke2_cni

- name: Copy Custom Manifests
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/lib/rancher/rke2/server/manifests/
    owner: root
    group: root
    mode: 0644
  with_items: "{{ rke2_custom_manifests_path }}"
  when: rke2_custom_manifests_path

- name: Copy Cilium HelmChart Configs
  ansible.builtin.template:
    src: rke2-cilium-config.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
    owner: root
    group: root
    mode: 0644
  when: rke2_cni