- hosts: servers,agents
  become: true
  gather_facts: true
  roles:
    - prerequirements
    - pre
    - rke2
  vars_files:
    - ../vars/general-config.yml

- hosts: "{{ groups.servers.0 }}"
  become: true
  gather_facts: true
  roles:
    - post
  vars_files:
    - ../vars/general-config.yml
